# Generated by Django 5.1.2 on 2025-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0002_create_default_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='trancherecord',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
    ]
