# Generated by Django 5.1.2 on 2025-06-18 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0003_trancherecord_vat_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('project_name', models.CharField(max_length=255)),
                ('unit_id', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tranche_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparc.tranchepayment')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('agent', 'tranche_payment')},
            },
        ),
    ]
