# Generated by Django 5.1.2 on 2025-06-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0004_receivable'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receivable',
            name='withholding_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
