# Generated by Django 5.1.2 on 2025-06-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0005_receivable_vat_amount_receivable_withholding_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trancherecord',
            name='vat_rate',
        ),
        migrations.DeleteModel(
            name='Receivable',
        ),
    ]
