# Generated by Django 5.1.2 on 2025-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0007_trancherecord_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trancherecord',
            name='net_of_vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
