# Generated by Django 5.1.2 on 2025-07-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0008_trancherecord_net_of_vat_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trancherecord',
            name='process_fee_percentage',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
    ]
