# Generated by Django 5.1.2 on 2025-08-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0012_billinginvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinginvoice',
            old_name='notes',
            new_name='bill_to_address',
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='bill_to_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='bill_to_tin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='service_invoice_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='terms',
            field=models.IntegerField(default=30, help_text='Payment terms in days'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
