# Generated by Django 5.1.2 on 2025-08-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0013_rename_notes_billinginvoice_bill_to_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
    ]
