# Generated by Django 5.1.2 on 2025-08-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0014_billinginvoice_notes_alter_billinginvoice_vat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginvoice',
            name='bill_to_address',
        ),
        migrations.RemoveField(
            model_name='billinginvoice',
            name='bill_to_name',
        ),
        migrations.RemoveField(
            model_name='billinginvoice',
            name='bill_to_tin',
        ),
        migrations.RemoveField(
            model_name='billinginvoice',
            name='service_invoice_no',
        ),
        migrations.RemoveField(
            model_name='billinginvoice',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='billinginvoice',
            name='updated_at',
        ),
    ]
