# Generated by Django 5.1.2 on 2025-08-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0015_remove_billinginvoice_bill_to_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
