# Generated by Django 5.1.2 on 2025-08-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0016_billinginvoice_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='client_address',
            field=models.TextField(default='2nd Flr B and S Bldg 1644 Evangelista St. Bangkal\nMakati City, Metro Manila 1233'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='client_name',
            field=models.CharField(default='650 ALLIED INC.', max_length=255),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='client_tin',
            field=models.CharField(default='755-023-386-000', max_length=50),
        ),
    ]
