# Generated by Django 5.1.2 on 2025-08-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0018_billinginvoice_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='approved_by_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='checked_by_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='prepared_by_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
