# Generated by Django 5.1.2 on 2025-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0019_billinginvoice_approved_by_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='prepared_by_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
