# Generated by Django 5.1.2 on 2025-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0020_billinginvoice_prepared_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionslip',
            name='manager_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='commissionslip',
            name='sales_manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
