# Generated by Django 5.1.2 on 2025-08-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0021_commissionslip_manager_commission_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionslip',
            name='team_leader_tax_rate',
        ),
    ]
