# Generated by Django 5.1.2 on 2025-08-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0022_remove_commissionslip_team_leader_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionslip2',
            name='team_leader_rate',
        ),
    ]
