# Generated by Django 5.1.2 on 2025-08-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0023_remove_commissionslip2_team_leader_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
