# Generated by Django 5.1.2 on 2025-08-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0024_delete_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionslip',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
