# Generated by Django 5.1.2 on 2025-08-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0027_problemreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemReport',
        ),
    ]
