# Generated by Django 5.1.2 on 2025-08-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0029_problemreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranchepayment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
