# Generated by Django 5.1.2 on 2025-08-21 08:18

from django.db import migrations

def update_status_to_pending(apps, schema_editor):
    """
    Update status from 'On Process' to 'Pending' for all TranchePayment instances.
    """
    TranchePayment = apps.get_model('sparc', 'TranchePayment')
    TranchePayment.objects.filter(status='On Process').update(status='Pending')

def revert_status_to_on_process(apps, schema_editor):
    """
    Revert status from 'Pending' to 'On Process' for records that were not originally 'Partial' or 'Received'.
    This is a best-effort reversal.
    """
    TranchePayment = apps.get_model('sparc', 'TranchePayment')
    # This will revert all 'Pending' statuses, which is the intended reverse action for this specific migration.
    TranchePayment.objects.filter(status='Pending').update(status='On Process')

class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0030_alter_tranchepayment_status'),
    ]

    operations = [
        migrations.RunPython(update_status_to_pending, reverse_code=revert_status_to_on_process),
    ]
